Libro.BL/Controllers/AutorController.cs
using LibroBL.Models;
using LibroBL.Repositorio;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibroBL.Controllers
{
    public class AutorController : Controller
    {
        AutorRepositorio foo = new AutorRepositorio();
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("Tipo") == "Administrador")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public IActionResult ListaAutor()
        {
            if (HttpContext.Session.GetString("Tipo") == "Administrador")
            {
                return View("ListaAutor", foo.GetAutores());
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public IActionResult AgregarAutor()
        {
            if (HttpContext.Session.GetString("Tipo") == "Administrador")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public IActionResult AgregarAutorDB(Autor autor)
        {
            if (HttpContext.Session.GetString("Tipo") == "Administrador")
            {
                foo.Agregar(autor);
                return RedirectToAction("ListaAutor");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public IActionResult BuscarAutor(Autor autor)
        {
            if (HttpContext.Session.GetString("Tipo") == "Administrador")
            {
                var HelperAutor = foo.GetAutor(autor.Id);
                return View(HelperAutor);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public IActionResult EditarAutor(int id)
        {
            if (HttpContext.Session.GetString("Tipo") == "Administrador")
            {
                var autor = foo.GetAutor(id);
                return View("EditarAutor", autor);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public IActionResult EditarAutorSend(Autor autor)
        {
            if (HttpContext.Session.GetString("Tipo") == "Administrador")
            {
                foo.EditSend(autor);
                return RedirectToAction("ListaAutor");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public IActionResult BorrarAutor(Autor autor)
        {
            if (HttpContext.Session.GetString("Tipo") == "Administrador")
            {
                foo.Remove(autor.Id);
                return RedirectToAction("ListaAutor");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public IActionResult EliminarAutor()
        {
            if (HttpContext.Session.GetString("Tipo") == "Administrador")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public IActionResult FindAutor()
        {
            if (HttpContext.Session.GetString("Tipo") == "Administrador")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }


    }
}

Libro.BL/Controllers/EstudianteController.cs
using LibroBL.Models;
using LibroBL.Repositorio;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibroBL.Controllers
{
    //Colocar los validadores de los requests
    public class EstudianteController : Controller
    {
        EstudianteRepositorio foo = new EstudianteRepositorio();
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AgregarEstudiante()
        {
            return View();
        }
        public async Task<IActionResult> ListaEstudiante()
        {
            var list = await foo.GetEstudiante();
            return View(list);
        }

        public async Task<IActionResult> AgregarEstudianteDB(UsuarioEstudiante estudiante)
        {
            foo.Agregar(estudiante);
            return RedirectToAction("ListaEstudiante");
        }

        public async Task<IActionResult> BuscarEstudiante(Estudiante estudiante)
        {
            var HelperEstudiante = await foo.GetEstudiante(estudiante.NumeroEstudiante);
            return View(HelperEstudiante);
        }

        public async Task<IActionResult> EditarEstudiante(int id)
        {
            var estudiante = await foo.GetEstudiante(id);
            return View("EditarEstudiante", estudiante);
        }

        public async Task<IActionResult> EditarEstudianteSend(Estudiante estudiante)
        {
            foo.EditSend(estudiante);
            return RedirectToAction("ListaEstudiante");
        }

        public IActionResult BorrarEstudiante(Estudiante estudiante)
        {
            foo.Remove(estudiante.NumeroEstudiante);
            return RedirectToAction("ListaEstudiante");
        }

        public IActionResult EliminarEstudiante()
        {
            return View();
        }

        public IActionResult FindEstudiante()
        {
            return View();
        }
    }
}

Libro.BL/Controllers/LibroController.cs
using LibroBL.Models;
using LibroBL.Repositorio;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibroBL.Controllers
{
    public class LibroController : Controller
    {
        LibroRepositorio foo = new LibroRepositorio();
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("Tipo") == "Administrador")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public IActionResult ListaLibro()
        {
            var colLibros = foo.GetLibros();
            return View(colLibros);
        }

        public IActionResult AgregarLibro()
        {
            if (HttpContext.Session.GetString("Tipo") == "Administrador")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public IActionResult AgregarLibroDB(Libro libro)
        {
            if (HttpContext.Session.GetString("Tipo") == "Administrador")
            {
                foo.Agregar(libro);
                return RedirectToAction("ListaLibro");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public IActionResult LibroEstudiante(Libro libro)
        {
            if (HttpContext.Session.GetString("Tipo") == "Administrador")
            {
                var hlibro = foo.GetLibro(libro.Isbn);
                return View("EditarLibro", hlibro);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public IActionResult EditarLibro(int Isbn)
        {
            if (HttpContext.Session.GetString("Tipo") == "Administrador")
            {
                var libro = foo.GetLibro(Isbn);
                return View(libro);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public IActionResult EditSend(Libro libro)
        {
            if (HttpContext.Session.GetString("Tipo") == "Administrador")
            {
                foo.EditSend(libro);
                return RedirectToAction("ListaLibro");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public IActionResult DetalleLibro(Libro libro)
        {
            if (HttpContext.Session.GetString("Tipo") == "Administrador")
            {
                var Hlibro = foo.GetLibro(libro.Isbn);
                return View(Hlibro);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public IActionResult BorrarLibro(Libro libro)
        {
            if (HttpContext.Session.GetString("Tipo") == "Administrador")
            {
                foo.Remove(libro.Isbn);
                return RedirectToAction("ListaLibro");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
        public IActionResult EliminarLibro()
        {
            if (HttpContext.Session.GetString("Tipo") == "Administrador")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public IActionResult FindLibro()
        {
            if (HttpContext.Session.GetString("Tipo") == "Administrador")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
    }
}

Libro.BL/Controllers/PrestamoController.cs
using LibroBL.Models;
using LibroBL.Repositorio;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Permissions;
using System.Threading.Tasks;

namespace LibroBL.Controllers
{
    public class PrestamoController : Controller
    {
        PrestamoRepositorio foo = new PrestamoRepositorio();
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PrestamosActuales()
        {
            var prestamos = foo.ListaPrestamo();
            return View(prestamos);
        }

        public IActionResult BuscarEstudiante()
        {
            return View();
        }

        public IActionResult PrestamosActualesEstudiante(Estudiante estudiante)
        {
            PrestamoEstudiante prestamos;

            if (HttpContext.Session.GetString("NumeroEstudiante") != null)
            {
                prestamos = foo.BuscarPrestamoID(int.Parse(HttpContext.Session.GetString("NumeroEstudiante")));
            }
            else
            {
                prestamos = foo.BuscarPrestamoID(estudiante.NumeroEstudiante);
            }
            return View("PrestamosActualesPorEstudiante", prestamos);
        }

        public IActionResult PrestamosActualesPorEstudiante()
        {
            return View();
        }

        public IActionResult CrearPrestamo(int? ISBN)
        {
            HttpContext.Session.SetString("ISBN", ISBN.ToString());
            return View();
        }

        public IActionResult CrearPrestamoDB(Prestamo prestamo)
        {

            if (HttpContext.Session.GetString("NumeroEstudiante") != null)
            {
                Estudiante estu = new Estudiante(); 
                estu.NumeroEstudiante = int.Parse(HttpContext.Session.GetString("NumeroEstudiante"));
                prestamo.Isbn = int.Parse(HttpContext.Session.GetString("ISBN"));
                prestamo.NumeroEstudiante = int.Parse(HttpContext.Session.GetString("NumeroEstudiante"));
                foo.CrearPrestamo(prestamo);
                return RedirectToAction("PrestamosActualesEstudiante", estu);
            }
            else
            {
                foo.CrearPrestamo(prestamo);
                return RedirectToAction("PrestamosActuales");
            };
        }

        public IActionResult EliminarPrestamo(int Isbn, int NumeroEstudiante)
        {


            if (HttpContext.Session.GetString("NumeroEstudiante") != null)
            {
                Estudiante estu = new Estudiante();
                estu.NumeroEstudiante = int.Parse(HttpContext.Session.GetString("NumeroEstudiante"));
                foo.EliminarPrestamo(Isbn, NumeroEstudiante);
                return RedirectToAction("PrestamosActualesEstudiante", estu);
            }
            else
            {
                foo.EliminarPrestamo(Isbn, NumeroEstudiante);
                return RedirectToAction("PrestamosActuales");
            }

        }
    }
}

Libro.BL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibroBL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Biblioteca</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="nav navbar-nav ml-auto">
                        @if (HttpContextAccessor.HttpContext.Session.GetString("Tipo") == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Index"><span class="fas fa-sign-in-alt"></span>Log In</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Login" asp-action="LogoutUser"><span class="fas fa-sign-in-alt"></span>Log Out</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (HttpContextAccessor.HttpContext.Session.GetString("Tipo") == "Administrador")
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Gestion de datos
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Autor" asp-action="Index">Autores</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Libro" asp-action="Index">Libros</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Estudiante" asp-action="Index">Estudiantes</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Prestamos
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Prestamo" asp-action="PrestamosActuales">Actuales</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Prestamo" asp-action="BuscarEstudiante">Por estudiante</a>
                                </div>
                            </li>
                        }
                        @if (HttpContextAccessor.HttpContext.Session.GetString("Tipo") == "Estudiante")
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Estudiante
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Libro" asp-action="ListaLibro">Listado de libros</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Prestamo" asp-action="PrestamosActualesEstudiante">Libros en prestamo</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Libro" asp-action="ListaLibro">Pedir libro</a>
                                </div>
                            </li>
                        }
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - LibroBL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>